version: '3.7'

networks:
  traefik-public:
    external: true
#  interna:
#    external: false

services:
  laravel:
    #nome do container definido usando o valor da variável
    container_name: laravel-php8.1
    #imagem do container que será baixada do repositório dockerhub ou harbor
    #image: harbor.dev.cbm.al.gov.br/dev-local/cakephp:5.6
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    image: gbzzz/laravel-php8.1
    #image: nginxdemos/hello
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - traefik-public
 #     - interna
    #seção onde é definida a montagem bind para o volume da aplicação em desenvolvimento
    #Necessário mapear diretório do host que contém a aplicação a ser desenvolvida
    volumes:
      - /c/projetos/Ficker/ficker-back-end:/app
    environment:
      - APP_ENV=local
    labels:
      - traefik.enable=true
      - traefik.network=traefik-public
      #definição da porta de entrada do traefik proxy
      #- traefik.http.routers.laravel-rtr.entrypoints=websecure
      #definição da rota via traefik proxy
      - traefik.http.routers.laravel-rtr.rule=Host(`ficker.localhost`)
      - traefik.http.routers.laravel-rtr.tls=true
      # - traefik.http.routers.laravel-rtr.tls.certresolver=letsencrypt
      #definição do serviço via traefik proxy
      - traefik.http.services.laravel-svc.loadbalancer.server.port=80
      # - traefik.http.routers.laravel-rtr.middlewares=basic-auth@file